"$schema" = "./tsumiki.schema.json"

[battery]
full_battery_level = 100
hide_label_when_full = true
label = true
tooltip = true

[bluetooth]
icon_size = 14
label = true
tooltip = true

[brightness]
icon_size = "14px"
label = true
tooltip = true
step_size = 5

[cava]
bars = 10

[click_counter]
count = 0

[cpu]
icon = ""
icon_size = "12px"
label = true
tooltip = true
unit = "celsius"
round = true
show_unit = true
sensor = "acpitz"

[date_time]
format = "%b %d %H:%M"
notification_count = true
notification = true
calendar = true
clock_format = "24h",
uptime = true

[divider]
size = 2

[hypridle]
enabled_icon = ""
disabled_icon = ""
icon_size = "12px"
label = true
tooltip = true

[hyprsunset]
temperature = "2800k"
enabled_icon = "󱩌"
disabled_icon = "󰛨"
icon_size = "12px"
label = true
tooltip = true

[keyboard]
icon = "󰌌"
icon_size = "14px"
label = true
tooltip = true

[language]
truncation_size = 2
icon_size = "14px"
tooltip = true
icon = ""

[layout]
left_section = [ "workspaces", "window_title" ]
middle_section = [ "date_time" ]
right_section = [ "recorder", "@collapsible:0", "@group:0", "system_tray" ]

[[widget_groups]]
widgets = [ "updates", "ocr", "battery" ]
spacing = 4
style_classes = [ "compact" ]

[[widget_groups]]
widgets = [ "quick_settings", "cpu" ]
spacing = 0
style_classes = [ "compact" ]

# Collapsible groups create popup menus with utility widgets, accessed as @collapsible:0, @collapsible:1, etc
[[collapsible_groups]]
widgets = [
    "cliphist",
    "emoji_picker",
    "ocr",
    "screenshot",
    "recorder"
]
spacing = 4
icon = "󰒓"  # icon for the collapsible group button
tooltip = "Utility Tools"  # tooltip for the collapsible group button
style_classes = [ "utility-tools" ]

[memory]
icon = ""
icon_size = "12px"
label = true
tooltip = true

[submap]
icon = "󰌌"
icon_size = "12px"
label = true
tooltip = true

[microphone]
icon_size = "12px"
label = false
tooltip = true

[ocr]
icon = "󰐳"
icon_size = "14px"
tooltip = true
label = true

[mpris]
truncation_size = 200
tooltip = true

[notification]
anchor = "top-right"
auto_dismiss = true
ignored = [ ]
timeout = 3_000
play_sound = true
sound_file = "notification4"
max_count = 5

[osd]
enabled = true
timeout = 1_500
anchor = "bottom-center"
percentage = true
icon_size = 28

[general]
check_updates = false
layer = "top"
auto_hide = false
debug = true
location = "top"
widget_style = "default"

  [general.screen_corners]
  enabled = false
  size = 20

  [general.desktop_clock]
  enabled = true
  anchor = "bottom-right"
  date_format = "%A, %d %B %Y"

[power]
icon = "󰐥"
icon_size = "18px"
tooltip = true

[recorder]
path = "Videos/Screencasting"
audio = true
icon_size = 16
tooltip = true

[spacing]
size = 20

[network_usage]
icon_size = "14px"
upload_icon = ""
download_icon = ""
tooltip = true
upload = true
download = false

[quick_settings.media]
ignore = [ ]
truncation_size = 30
show_album = true
show_artist = true
show_time = true
show_time_tooltip = true

[[quick_settings.shortcuts]]
icon = "terminal-symbolic"
label = "Terminal"
command = "kitty"
tooltip = "Open terminal"
icon_size = 18

[[quick_settings.shortcuts]]
icon = "firefox-symbolic"
label = "Browser"
command = "firefox"
tooltip = "Launch Firefox"
icon_size = 18

[stopwatch]
stopped_icon = "󱫞"
running_icon = "󱫠"
icon_size = "16px"

[storage]
icon = "󰋊"
icon_size = "14px"
label = true
tooltip = true

[system_tray]
icon_size = 16
ignored = [ ]
hidden = [ ]
hide_when_empty = false

[taskbar]
icon_size = 22

[theme]
name = "catpuccin-mocha"

[theme_switcher]
icon = ""
icon_size = "14px"
notify = false

[updates]
os = "arch"
icon = "󱧘"
icon_size = "14px"
interval = 3_600_000
tooltip = true
label = true

[volume]
icon_size = "14px"
label = true
tooltip = true
step_size = 5

[weather]
location = ""
label = true
tooltip = true
interval = 3_600_000

[window_title]
icon = true
truncation = true
truncation_size = 50
title_map = [ ]

[workspaces]
count = 8
hide_unoccupied = true
default_label_format = "{id}"
ignored = [ -99 ]
reverse_scroll = false
empty_scroll = false
icon_map = { }

[cliphist]
icon = ""
label = false
tooltip = true

[emoji_picker]
icon = ""
label = false
tooltip = true

[screenshot]
path = "Pictures/Screenshots"
icon_size = 16
tooltip = true
label = false
annotation = true
capture_sound = true
icon = "󰄀"

[hyprpicker]
icon = ""
tooltip = true
label = false
show_icon = true

[kanban]
icon = "󱞁"
label = false
tooltip = true
